Change the Netframework to 2.0 (only Network-JSON)
If we use JSON 3.5, program throw Exception.

Assets/Script/Network/NetworkMain.cs(26,49): error CS7069: Reference to type `System.ComponentModel.INotifyPropertyChanging' claims it is defined assembly `System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found
.